### ISSUE TITLE
Question: android 9?

### ISSUE THREAD

**Issue by eurodyke** [ThePBone/RootlessJamesDSP#101]
Hi,
I'm wondering, since the rooted-version of JamesDSP works from android 5, will RootlessJamesDSP ever be available for some earlier android versions? I'm mostly wondering about android 9 (since I know it is the earliest android version you can use Poweramp EQ on). I do fully understand if never will be possible, but I'm asking since I'd like to use a systemwide convolver on an non-rootable android 9 device.

Thanks for your great application (I use it on my other phone).

**Comment by ThePBone** [comment]
Unfortunately no. Poweramp EQ and similar apps/features all re-use the standard EQ & audio effects built into Android. They cannot apply custom/advanced effects because they don't have direct access to the audio data played by other apps.

Because RootlessJDSP needs direct access to audio data, it also needs to record internal audio output. However, that Android feature was only universally available as a public developer API since Android 10, so I cannot support Android 9 and lower.

**Comment by eurodyke** [comment]
I understand! Thank you for the great app!
