### ISSUE TITLE
[Workaround] Repeated audio / Endless echo

### ISSUE THREAD

**Issue by octoghost** [ThePBone/RootlessJamesDSP#109]
I discovered a workaround that works on my device: add RootlessJamesDSP itself to the "Excluded Apps" list.

As I understand it, some Android custom ROMs include patches to make sure that apps can't block their sound from being captured. This way RootlessJamesDSP unrestrictedly captures itself in an infinite loop.

I couldn't find any explanation for this problem online, so I'm hoping this can be helpful to someone experiencing the same problem.

Thanks for your hard work in developing this wonderful app.

**Comment by terminal-cs** [comment]
Interesting, I'll try this later.

**Comment by terminal-cs** [comment]
> Interesting, I'll try this later.

Yep, seems to fix the issue

**Comment by ThePBone** [comment]
This app normally plays the processed audio using the `ALLOW_CAPTURE_BY_NONE` audio policy flag, which should prevent other apps, including itself, from being recorded.
But since some ROMs seem to disregard this flag, I have set this as the default now with commit 91698742.

I haven't published a new stable release yet, but precompiled APKs with the fix can be downloaded from GitHub actions in a few minutes: https://github.com/ThePBone/RootlessJamesDSP/actions/runs/6316049527
