### ISSUE TITLE
Stuck on 1.2.2/F-Droid behind

### ISSUE THREAD

**Issue by Ricat87** [ThePBone/RootlessJamesDSP#59]
Hi, I installed from F-Droid (Droid-ify frontend), and the version I'm seeing there is way behind even after repeatedly refreshing the repo.

If I look on the Play Store it thinks I'm up to date, so I can't do anything from there unless I uninstall. 

I might be missing something but it seems like the release page only has zips of the source code and not a built apk to download.

Is it recommended to only use the Play Store version?

**Comment by ThePBone** [comment]
Hi, the F-Droid release is always delayed by a few days because that's how the F-Droid repo works. I fully support both the F-Droid & Play Store version alike. There is no recommended version between them.

F-Droid builds all the app updates on their own servers every few days. Then a person from their team takes all the compiled APKs and signs them on an air-gapped/offline computer with F-Droid's trusted signing key (for security reasons). Because this is a manual process, it may take another few days to finish the process.

F-Droid updates are generally delayed by about 2 to 6 days because of that procedure.

Currently, the last three updates (v1.3.0-v1.3.2) for RootlessJamesDSP are still stuck in the current build cycle, which you can view here: https://monitor.f-droid.org/builds/running (look for `me.timschneeberger.rootlessjamesdsp`).
I'm guessing it will take another 2 days until the update is available in the F-Droid repo.

Anyway, Google Play doesn't allow you to update because the signatures of the F-Droid and Play Store versions are different. You would need to completely uninstall the F-Droid version if you wanted to use Google Play for updates instead.
(Note: Make sure to backup the presets/configuration at `/sdcard/Android/data/me.timschneeberger.rootlessjamesdsp` before uninstalling; otherwise, the data may be removed.)
