### ISSUE TITLE
Automatically re-enable on reboot if PROJECT_MEDIA permission is granted with ADB

### ISSUE THREAD

**Issue by mariobrostech** [ThePBone/RootlessJamesDSP#76]
Hi,

I recently finished setting up JamesDSP on my device, and I'm really enjoying it so far! However, there is one inconvenience that I hope might be fixable. I used ADB to set everything up, and I enabled the optional feature to skip audio capture permission prompts (`appops set me.timschneeberger.rootlessjamesdsp PROJECT_MEDIA allow`). However, even after having done this, the app still displays a notification upon rebooting that user input is required to launch JamesDSP. Tapping on that notification causes it to dismiss itself and enable JamesDSP. Can the app check for the PROJECT_MEDIA permission at runtime and automatically activate without user interaction if it has already been granted? This is only possible if the permission had previously been enabled using ADB, so I don't consider this to be a privacy concern. If the user doesn't grant the optional permission with ADB, Android will still have to get explicit approval from the user before the PROJECT_MEDIA permission will be enabled; therefore, if JamesDSP queries the status of the PROJECT_MEDIA permission at runtime and it's enabled, the user would have to have enabled the permission via ADB.

Thanks in advance!

**Comment by mariobrostech** [comment]
That sounds good, thank you! I don't know if it accomplishes quite the same effect, but I've seen other apps like K-9 Mail use Android's Alarms & Reminders permissions to achieve a similar effect so it can scan for push emails in the background. Maybe that's something that could be explored as well. As far as I know, it's completely transparent to the user since it's enabled by default for any app that requests it. The user can disable this functionality, but they wouldn't know that it even existed unless they go into the App Info page where it's displayed as an option.

**Comment by ThePBone** [comment]
I tried to use the Alarms & Reminders permissions, but unfortunately, it only allows background processes to launch foreground services but not activities. I used the approach I talked about earlier instead.

It requires the `SYSTEM_ALERT_WINDOW` permission which can be granted in Android's settings or using this ADB command:
```
appops set me.timschneeberger.rootlessjamesdsp SYSTEM_ALERT_WINDOW allow
```

If a user sets the app up using Shizuku, all of that is done automatically. Otherwise, the instructions for ADB setup mention this as an optional step. You can now also go to 'Settings > Misc > Optional permissions' to check if the permissions are already granted and whether auto-start is available.

_____________________

Updated APKs (v1.5.0) are already available here: [ThePBone/RootlessJamesDSP/actions/runs/4514747380](https://github.com/ThePBone/RootlessJamesDSP/actions/runs/4514747380)
(Signed with the same key as the Play Store release, so you can easily update without uninstalling due to package signature conflicts.)

The actual Google Play release probably takes until Monday because the app reviewing process is slower on weekends.
