### ISSUE TITLE
[Suggestion] Excluded audio outputs/devices

### ISSUE THREAD

**Issue by FrameXX** [ThePBone/RootlessJamesDSP#77]
I think it would be really useful for a lot of users to be able to exclude certain audio devices from audio processing in the very same way as we can do it with apps. By audio outputs/devices I mean for example "Phone reproductor", "Cable headphones", "Bose Quietcomfort", "Sennheiser X3784 whatever...". The same output devices we can choose from in android media output picker. I don't know if it's possible for user apps to detect the current output device, but I hope it is.

**Comment by ThePBone** [comment]
This feature is included in v1.5.0. 

You can already grab APKs here: https://github.com/ThePBone/RootlessJamesDSP/actions/runs/4514747380
(Signed with the same key as the Play Store release, so you can easily update without uninstalling due to package signature conflicts.)

The actual Google Play release probably takes until Monday because the app reviewing process is slower on weekends. 
_____
If you use the root version, go to 'Settings > About > Check for updates...' and use the in-app updater.
